name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            echo 'Deployment Started'
            pm2 start npm -- start
            pm2 delete all
            echo 'Pull from github'
            cd pinkHawk
            git pull origin main
            echo 'Server Deployment Started'
            cd server
            npm install
            echo 'Apply migration'
            npx prisma migrate dev
            pm2 start npm -- start
            echo 'Server Deployment Done'
            echo 'Client Deployment Started'
            cd ../client
            cp -r ./build/* /var/www/pinkhawk.xyz/html
            echo 'Client Deployment Done'
